name: _fe_analyzer_shared
version: 41.0.0
description: Logic that is shared between the front_end and analyzer packages.
repository: https://github.com/dart-lang/sdk/tree/main/pkg/_fe_analyzer_shared

environment:
  sdk: '>=2.12.0 <3.0.0'
  firebase_database: ^10.0.15
  firebase_core: ^2.7.1
  firebase_analytics: ^10.1.5
  flutter_switch: ^0.2.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0




dependencies:
  meta: ^1.0.2
  http: ^0.13.3


# We use 'any' version constraints here as we get our package versions from
# the dart-lang/sdk repo's DEPS file. Note that this is a special case; the
# best practice for packages is to specify their compatible version ranges.
# See also https://dart.dev/tools/pub/dependencies.
assets:
  - images/
dev_dependencies:
  test: any
